export const frontStaticTypes = {
   RESET_FRONT_STATIC: 'RESET_FRONT_STATIC',
   SET_FRONT_STATIC_DATA: 'SET_FRONT_STATIC_DATA',
   SET_FRONT_STATIC_FAQ: 'SET_FRONT_STATIC_FAQ',
   SET_FRONT_STATIC_CONTACTS: 'SET_FRONT_STATIC_CONTACTS',
   //  SET_FAQ: 'SET_FAQ',
   //  SET_CONTACTS: 'SET_CONTACTS',
   //  SET_BLOG_CATEGORY: 'SET_BLOG_CATEGORY',
   //  SET_PAGES: 'SET_PAGES',
   //  SET_PAGE: 'SET_PAGE',
}
