export const frontCoursesTypes = {
   SET_FRONT_COURSES_DATA: 'SET_FRONT_COURSES_DATA',
   SET_FRONT_COURSES: 'SET_FRONT_COURSES',
   SET_FRONT_COURSE: 'SET_FRONT_COURSE',
   SET_FRONT_INTERESTES: 'SET_FRONT_INTERESTES',
   SET_FRONT_DESCRIPTIONS: 'SET_FRONT_DESCRIPTIONS',
   SET_FRONT_PRICES: 'SET_FRONT_PRICES',
   SET_FRONT_TRAINER: 'SET_FRONT_TRAINER',
   SET_FRONT_MODULES: 'SET_FRONT_MODULES',
   SET_FRONT_LESSONS: 'SET_FRONT_LESSONS',
   SET_FRONT_WHOMS: 'SET_FRONT_WHOMS',
}
