export const authTypes = {
    SET_AUTH: 'SET_AUTH',
    SET_USER: 'SET_USER',
    SET_TOKEN: 'SET_TOKEN',
    SET_ERROR: 'SET_ERROR',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_SHOW_MODAL: 'SET_SHOW_MODAL',
    SET_STEP: 'SET_STEP',
}
