export { default as About } from './About'
export { default as AddLesson } from './AddLesson'
export { default as Events } from './Events'
export { default as Home } from './Home'
export { default as Lessons } from './Lessons'
export { default as News } from './News'
export { default as Subscribe } from './Subscribe'
