export { default as Blog } from './Blog'
export { default as BlogItem } from './BlogItem'
export { default as Cabinet } from './Cabinet'
export { default as CabinetCoursesAdd } from './CabinetCoursesAdd'
export { default as CabinetCoursesItem } from './CabinetCoursesItem'
export { default as CabinetCoursesLessons } from './CabinetCoursesLessons'
export { default as CabinetCoursesLesson } from './CabinetCoursesLesson'
export { default as CabinetCoursesLessonTest } from './CabinetCoursesLessonTest'
export { default as CabinetEventsAdd } from './CabinetEventsAdd'
export { default as CabinetEventsItem } from './CabinetEventsItem'
export { default as Contacts } from './Contacts'
export { default as Courses } from './Courses'
export { default as CoursesItem } from './CoursesItem'
// export { default as CoursesLesson } from './CoursesLesson'
export { default as Events } from './Events'
export { default as EventsItem } from './EventsItem'
export { default as Faq } from './Faq'
export { default as Home } from './Home'
export { default as News } from './News'
// export { default as NewsItem } from './NewsItem'
export { default as PagesItem } from './PagesItem'
export { default as Partners } from './Partners'
export { default as Reviews } from './Reviews'
export { default as Subscribe } from './Subscribe'
export { default as Error } from './Error'
export { default as Logout } from './Logout'
export { default as UsersItem } from './UsersItem'
