export const coursesTypes = {
    SET_COURSES: 'SET_COURSES',
    SET_COURSE: 'SET_COURSE',
    SET_MODULES: 'SET_MODULES',
    SET_INFO: 'SET_INFO',
    SET_LESSONS: 'SET_LESSONS',
    SET_LESSON: 'SET_LESSON',
    SET_LESSON_QUESTIONS: 'SET_LESSON_QUESTIONS',
    SET_LESSON_FILES: 'SET_LESSON_FILES',
    SET_LESSON_FILE: 'SET_LESSON_FILE',
    ADD_LESSON_FILE: 'ADD_LESSON_FILE',
}
