export const coursesTypes = {
    SET_COURSES: 'SET_COURSES',
    SET_COURSE: 'SET_COURSE',
    SET_MODULES: 'SET_MODULES',
    SET_LESSONS: 'SET_LESSONS',
    SET_LESSON: 'SET_LESSON',
    SET_INFO: 'SET_INFO',
}
