export const frontEventsTypes = {
   RESET_FRONT_EVENTS: 'RESET_FRONT_EVENTS',
   SET_FRONT_EVENTS_DATA: 'SET_FRONT_EVENTS_DATA',
   SET_FRONT_EVENTS: 'SET_FRONT_EVENTS',
   SET_FRONT_EVENT: 'SET_FRONT_EVENT',
}
